### ISSUE TITLE
Make the from_json displayed policy statement drop the "when {true}" clause if the when clause is empty

### ISSUE THREAD

**Issue by Swolebrain** [cedar-policy/cedar#125]
### Category

User level API changes

### Describe the feature you'd like to request

Problem: When providing an EST to the `Policy::from_json` method, then displaying that policy, the displayed policy contains `when {true}`.

Not sure about best implementation, but a blanket update to `Policy`'s `Display` trait might not be what we want. This would swallow `when {true}` clauses even if the customer wants it there (because they're using a different flow).

### Describe the solution you'd like

Expectation: if an EST has no conditions, we should not render a when clause. 

### Describe alternatives you've considered

string parsing - not ideal

### Additional context

This is used in building gui tools for policy authoring

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by shaobo-he-aws** [comment]
Hi @Swolebrain. thank you for creating this issue. Could you please clarify further on the motivation why we don't want clauses containing `true` printed?

**Comment by cdisselkoen** [comment]
I'll take on this issue.  Some context for the thread:

The current `Display` impl for `cedar_policy::Policy` prints the AST, not the EST or anything else.  The AST is "lossy" and doesn't encode sufficient information to reconstruct the original policy.  Here, that manifests as, AST policies always have a "condition", with policies lacking conditions just getting constant `true`; so when displaying, there's no way to know if the original policy had no condition or actually had `when { true }`.  As another example of a lossy desugaring that happens when constructing an AST, any operations using `>` are converted to be expressed in terms of `<`; it's impossible to tell from just the AST whether the original policy used `>` or `<`.

As a result, displaying the AST is almost certainly not what @Swolebrain wants, for the stated purpose of "building gui tools for policy authoring".  Instead, that probably requires a lossless representation.  The EST is lossless, but currently doesn't have a `Display` impl itself, so to display an EST, you're stuck converting it to AST and then displaying, which runs into the problems described above (it loses information).  Instead, we need a real, direct EST printer (or perhaps EST --> CST, which could be done losslessly, and then display the CST; but I suspect a direct EST printer is the easier implementation).

**Comment by cdisselkoen** [comment]
I think it makes sense to fix #129 first, as that might have an impact on the implementation of this

**Comment by Swolebrain** [comment]
> Hi @Swolebrain. thank you for creating this issue. Could you please clarify further on the motivation why we don't want clauses containing `true` printed?

So that when people are creating policies using the policy helper in the AVP console, the policy they create comes out prettier.
