### ISSUE TITLE
Schema files should be able to refer to types in the empty namespace

### ISSUE THREAD

**Issue by john-h-kastner-aws** [cedar-policy/cedar#579]
### Category

Cedar validation features/changes

### Describe the feature you'd like to request

In the following schema, there is an `id` common type without a namespace. We should be able to refer to it inside of a namespace, but the schema currently doesn't parse because we implicitly qualify `id` with the current namespace, and then look for `Demo::id`. When this type isn't found, schema parsing fails.

```json
{
  "Demo": {
    "entityTypes": {
      "User": {
        "memberOfTypes": [],
        "shape": {
          "type": "Record",
          "attributes": {
            "id": { "type": "id" },
          }
        }
      }
    },
    "actions": {}
  },
  "": {
    "commonTypes": {
      "id": {
        "type": "String"
      },
    }
    "entityTypes": {},
    "actions": {}
  }
}
```

We should fix this in two ways:

* When `id` doesn't exist in the current namespace, we should fall back to looking for it in the empty/global namespace. This schema would then parse as expected.
* It should be possible to explicitly refer to types in the empty namespace. A possible syntax for this might be `{"type": "::id"}` (we should think about other possible syntax for this, and we also need a syntax for the human-readable schema format). This would allow referring to this definition of `id` even when another one is defined in this namespace.

The example in this issue uses `commonTypes`, but we should ensure that the behavior is consistent between `commonTypes`, `entityTypes` and `actions` which can all be qualified with a namespace.

**Comment by john-h-kastner-aws** [comment]
We've seen a couple different people encounter this issue now. Should make it a priority to get this fixed.

**Comment by shaobo-he-aws** [comment]
> We've seen a couple different people encounter this issue now. Should make it a priority to get this fixed.

We need to pin down some syntax for qualified names that refer to the empty namespace. Maybe an amendment to RFC 24?

**Comment by cdisselkoen** [comment]
The only syntax proposal I see in this thread is `::id` (for both the JSON and human formats). Is this:
* Basically settled, go with it
* Not settled but let's discuss here on this issue and make a decision quickly
* Not settled and we should have an RFC for discussion

**Comment by shaobo-he-aws** [comment]
> * Not settled and we should have an RFC for discussion

I prefer this path because I propose we leverage the soon-to-be-reserved `__cedar` namespaces. For instance, we could use something like `__cedar::schema::top_level::id`. My objection to `::id` is that it's not a valid `Name`.

**Comment by cdisselkoen** [comment]
If we do an RFC, that will delay the 3.2 release (RFC is probably a week for discussion + another week for FCP at minimum).

**Comment by cdisselkoen** [comment]
I'll open a PR to amend RFC 24 but not a separate RFC, unless folks push for a separate RFC for this.  This will hopefully avoid a 2-week+ decision process

**Comment by mwhicks1** [comment]
This is a small change and probably not controversial? Do we really need a full RFC for it?


Sent from my iPhone

On May 7, 2024, at 8:34 AM, Craig Disselkoen ***@***.***> wrote:

﻿

Eh I'm having second thoughts. While it makes sense to amend active RFCs with PRs, I don't think it makes sense to amend RFCs that have already landed and been released, with corresponding implementation PRs. If we did, it would make both the historical discussion and the original implementation PR look like they did things wrong or were confused. At this point, the RFC is more a record of the 2023 design discussion than it is ongoing documentation -- for ongoing documentation, we have two pages on docs.cedarpolicy.com and that's what we should keep up to date, not the RFC text.

I'll open a full RFC.

**Comment by cdisselkoen** [comment]
Opened [RFC 64](https://github.com/cedar-policy/rfcs/pull/64); closing this issue in favor of the RFC.

**Comment by cdisselkoen** [comment]
Reopening this issue, which represents just Change 2 from [RFC 64].  Change 2 is uncontroversial and deserves to be treated as a bug; it doesn't need an RFC itself.  So we're pulling Change 2 out of the RFC and back into this issue, leaving the other two more controversial changes (particularly Change 1) in the RFC.  Copying the description of Change 2 here for completeness:

### Change 2: Implicitly falling back on the empty namespace

When the schema refers to an unqualified typename (e.g, `id`) which doesn't exist in the active namespace, we should fall back to looking for it in the empty namespace. Only if it exists in neither the active nor empty namespace should this be an error.

E.g., in the example at the top of [RFC 64], consider the type of the `id` attribute of `Demo::User`. Since there is no `id` type defined in namespace `Demo`, this is an error today. With this change, when we see there is no `Demo::id`, we implicitly look for `id` in the empty namespace, and resolving `id` to be the common type `::id` defined to be `String` in the empty namespace. This change solves the common case where there is no collision (where `id` is not actually defined in both the `Demo` and empty namespaces); for the case where there actually is a collision, we have the other changes in [RFC 64], which will continue to be discussed there.

This applies to both entity and common types defined in the empty namespace.

This applies to both the human (RFC 24) and JSON schema syntaxes.

This is reminiscent of, but not dependent on, the existing similar behavior for primitive and extension types, where we first check for an entity or common type `String` in the active namespace before falling back on resolving to `__cedar::String`.

[RFC 64]: https://github.com/cedar-policy/rfcs/pull/64

**Comment by cdisselkoen** [comment]
In particular, this issue retains the scope of _only_ the implicit fallback, and _not_ the explicit syntax for referring to a (possibly shadowed) name in the empty namespace; the explicit syntax discussion continues in [RFC 64](https://github.com/cedar-policy/rfcs/pull/64).

**Comment by cdisselkoen** [comment]
I have this in progress but it's actually going to be a huge code change due to how our schema parsers are currently organized.  It probably won't be done soon

**Comment by cdisselkoen** [comment]
Noting a bunch of cases it will be important to test when resolving this issue:

We want to test all possible (position, scenario) pairs where:
- position is all places a typename can occur in a schema:
  - inside a context attribute type
  - inside an entity attribute type
  - inside an action attribute type
  - as an entity parent type
  - inside the body of a common-type definition
  - in an action parent declaration?
- scenario is all the ways a typename can resolve:
  - the typename is written without a namespace, and that typename is declared in the current namespace
    - as an entity type, or as a common type
  - the typename is written without a namespace, and that typename is declared in the empty namespace (but not the current namespace)
    - as an entity type, or as a common type
  - the typename is written _with_ a namespace
    - explicitly invoking the current namespace
    - invoking an unrelated namespace
    - note you can't explicitly invoke the empty namespace without RFC 64 (not accepted as of this writing)
- Repeating all of the above tests for both human syntax and JSON syntax

**Comment by john-h-kastner-aws** [comment]
Linking #711 as something to possibly resolve at the same time.
