### ISSUE TITLE
Semantic Versioning Support in Policies

### ISSUE THREAD

**Issue by driverpt** [cedar-policy/cedar#637]
### Category

Cedar language or syntax features/changes

### Describe the feature you'd like to request

Semantic Versioning comparison support for Conditions.

i.e.:
```
permit (principal, action == Action::"someAction", resource)
when {
    semVer(resource.apiVersion) >= semVer("1.0.0")
};
```

### Describe alternatives you've considered

N/A

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by driverpt** [comment]
Yes. Being able to use Cedar Policy to control access to API's based on Client Version

**Comment by aaronjeline** [comment]
In general we've avoided operator overloading. Would you be ok with:
```
semVer(resource.apiVersion).greaterThanOrEq(semVer("1.0.0"))
```
(This mirrors what we do for the `decimal` extension)

**Comment by driverpt** [comment]
Looks good!

**Comment by mwhicks1** [comment]
As an alternative you could encode `semver` as a record and then do attribute-wise comparisons. For example, a semver record could be `{ major: 1, minor: 0, patch: 0 }` to correspond to `1.0.0`, or `{ major: 2, minor: 0, patch: 1 }` to correspond to `2.0.1`. Then your particular policy would translate to:
```
permit (principal, action == Action::"someAction", resource)
when {
    resource.apiVersion.major >= 1 
};
```
A more involved comparison might be
```
permit (principal, action == Action::"someAction", resource)
when {
    resource.apiVersion.major >= 2 && resource.apiVersion.minor >= 1
    // api must be greater than 2.1.0
};
```
Would this work for you?

**Comment by cdisselkoen** [comment]
Nit: the second example doesn't correctly encode "api must be greater than 2.1.0", because for instance it fails for 3.0.0.  I think the correct policy would be

```
permit (principal, action == Action::"someAction", resource)
when {
    resource.apiVersion.major > 2 ||
    (resource.apiVersion.major == 2 && resource.apiVersion.minor >= 1)
};
```

**Comment by driverpt** [comment]
@cdisselkoen , there's a Rust Crate with SemVer that implements Comparison operators, it allows you to do something like my original example.

**Comment by aaronjeline** [comment]
This is addressed in the RFC for functions, which I think is a better way to handle this than adding an extensions. Take a look: https://github.com/cedar-policy/rfcs/blob/aaronjeline/functions/text/0059-functions.md

**Comment by driverpt** [comment]
Yes

**Comment by mwhicks1** [comment]
The Cedar developers met today to discuss and we came to the following conclusions:

1. We cannot implemented this issue as originally requested, using `>=`, `<`, etc. operators, because those operators are reserved for numbers.
2. We could imagine implementing it using an extension function/type (like `decimal` or `ipaddr`) as suggested by @aaronjeline above, e.g., `semVer(resource.apiVersion).greaterThanOrEq(semVer("1.0.0"))`. However, doing so requires updating the authorizer, validator, Lean models and proofs, differential tester, docs, etc. In other words, it's a non-trivial amount of work to implement and maintain. As a niche feature (we have not seen many requests for it), I'm afraid it does not rise to the level of something we can take on right now.
3. In the meantime, there is the workaround suggested in https://github.com/cedar-policy/cedar/issues/637#issuecomment-1943626178
4. Note that we wrote [RFC 61](https://github.com/cedar-policy/rfcs/pull/61) to make it possible for policy writers to define their own abstractions, like semver. Indeed, we motivated that RFC with semver! If you like the RFC, please upvote it. (It's also a heavy lift, but since it's a general feature that could be used for many things, we are more likely to implement it if there's sufficient demand.)
