### ISSUE TITLE
Change `EntityUID` to always be concrete

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar#72]
### Category

Other

### Describe the feature you'd like to request

Currently, an `EntityUID` stores a reference to its `EntityType`, which can be either `Concrete` or `Unspecified`. We introduced the `EntityType` type to support omitting entities in the input query. For example: when the "resource" of a query should have no impact on the authorization result, then users should not need to provide a resource entity when calling `is_authorized`.

However, we never actually expect an `EntityUID` to be "Unspecified", which leads to extra error handling code in several locations.

### Describe the solution you'd like

In CedarCore, the type `EntityUID` should always be concrete (i.e., its `EntityType` component should just be a `Name`), and  "Unspecified" entities should only be possible when constructing a `Query`. This requires some refactoring of the code, but should introduce no breaking changes.

### Describe alternatives you've considered

The current implementation works, but is more complicated than necessary.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [ ] ⚠️ This feature might incur a breaking change

**Comment by cdisselkoen** [comment]
Started implementing this and ran into the fact that the evaluator still needs to be able to evaluate unspecified entities, which means `Value` needs to be able to express unspecified entities.  I think we should add a case to `Literal`, or even better, change the `Literal::EntityUID` case to `Literal::Entity` with an enum specified/unspecified (so that existing code matching on `Literal::EntityUID` and assuming that covers all possible entity cases doesn't break).  This is of course a little bit of a stretch as unspecified entities are allowed as literals, but unspecified entity currently lives in the `ValueKind::Literal` arm of `Value`, so it's not making the situation worse than it already is.  Nonetheless, the complication of adding a case to `Literal` might negate the benefit of removing a case from `EntityType`.

**Comment by khieta** [comment]
Superseded by #919
