### ISSUE TITLE
Revisit record LUB definition

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar#87]
### Category

Cedar validation features

### Describe the feature you'd like to request

In the validation code the upper bound of the record types `{"foo" : Bool}` and `{"foo" : Int}` is defined as `{}`. This does not result in unsoundness, since the attribute "foo" can never be safely accessed from {}, but it is a little strange. It’s (arguably) more natural for this to be defined as an error since the types `Bool` and `Int` are inconsistent.

### Describe the solution you'd like

Update the LUB computation in the validator so that `{"foo" : Bool}` and `{"foo" : Int}` do not have an upper bound. This will mean that some policies that previously validated will now fail to validate. The potential benefit is that this change may allow for more useful error messages. For example, consider a (contrived) expression like `(if principal.is_user then {"foo" : true} else {"foo" : 2}).foo`. Validation will currently say that attribute `foo` cannot be safely accessed, while the actual issue is that the two possibilities for `foo` have incompatible types.

### Describe alternatives you've considered

The alternative is to leave the definition as-is. This is also a viable option -- it just depends on which we find more useful in practice.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request
- [X] ⚠️ This feature might incur a breaking change

**Comment by mwhicks1** [comment]
I don't believe that we should make this change, for two reasons.

1. The upper bound of the record types `{"foo" : Bool}` and `{"foo" : Int}` *is*  `{}`. If we are supporting width subtyping, we want this as the upper bound. A more relevant case might be the upper bound of `{ "foo": Bool, "bar": int }` and `{"foo": int, "bar": int }` being `{"bar": int}`. I can imagine cases where you have two records coming from different sources that have some common fields and some fields that happen to clash. I want the common fields in the LUB, I don't want an error.
2. Whatever we do with LUBs for records should have parity with entities. But then that would mean that the union type `A|B` may not actually exist if `A` and `B` have the same attribute with different types. This makes things more complicated, and it rules out the analogues of the "relevant case" example above.

Rather than make it an error, why not work to improve the error message for the situation you are mentioning? I think you should already get a good error message for the entity case, since `A|B` effectively retains all the field defs from both entities. Maybe you can implement "unions of records" to enable the same thing for records?

Another idea is to add a top type to the permissive validator. Then the LUB in your example would be `{"foo": top }`. The `if/then/else` would be allowed to typecheck but something like `(if principal.is_user then {"foo" : true} else {"foo" : 2}).foo + 2` would fail with an error indicating `foo` has top type, which perhaps you could label with metadata saying why.
