### ISSUE TITLE
JSON-human-JSON round-tripping fails on a schema with the empty namespace

### ISSUE THREAD

**Issue by shaobo-he-aws** [cedar-policy/cedar#907]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/cedar-policy/cedar/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/cedar-policy/cedar/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Bug Category

Schemas and Validation

### Describe the bug

After round-tripping, `{"": {"entityTypes": {}, "actions": {}}}` becomes `{}`.

### Expected behavior

The schema shouldn't change after round-tripping.

### Reproduction steps

```bash
echo '{"": {"entityTypes": {}, "actions": {}}}' | cargo run translate-schema --direction json-to-human | cargo run translate-schema --direction human-to-json
```

### Code Snippet

```rust
// Put your code below this line.

```

### Log output

```
// Put your output below this line

```

**Comment by cdisselkoen** [comment]
I'm not positive that this is a bug.  The new schema is equivalent to the old one, in that it defines exactly the same common types, entity types, and actions.  (That is, it defines no common types, entity types, or actions.)  What do we want this roundtrip to preserve?

* Textual equivalence?  Clearly not, because we don't want to preserve whitespace etc.
* Syntactic equivalence?  Including the ordering of declarations?
* Semantic equivalence?  That is, just that the roundtripped schema would have the same behavior (validate the same policies)?
